services:
  api:
    container_name: raffles-api
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    env_file: ".env"
    volumes:
      - ./storage/logs:/var/www/html/storage/logs
      - ./storage/app:/var/www/html/storage/app
    ports:
      - "8001:80"
    networks:
      - bet_online_network
networks:
  bet_online_network:
    driver: bridge
